# (4 December) Data Structures and NumPy:

##### Lists:

In [1]:
sample_list = [1,2.4,"sui",10]
sample_list

[1, 2.4, 'sui', 10]

In [2]:
sample_list[2]

'sui'

##### Lists are heterogenous - allows different types of elements (datatypes)

In [3]:
sample_list[8]

IndexError: list index out of range

##### Lists are mutable - values changeable

In [4]:
sample_list[1]=5
sample_list

[1, 5, 'sui', 10]

##### Tuples:

In [6]:
sample_tuple = (1,2,3,4,5)

In [7]:
sample_tuple

(1, 2, 3, 4, 5)

##### Tuples are also heterogenous

In [11]:
sample_tuple[2]

3

sample_tuple[2]=5

##### Tuples are immutable - TypeError

In [14]:
t=1,2,3,4,5

In [15]:
t

(1, 2, 3, 4, 5)

##### Assigning without (); considered a tuple

In [16]:
sample_tuple[2]

3

##### Sets:

In [63]:
sample_set={1,2,"one","two",3,3,"three"}
sample_set

{1, 2, 3, 'one', 'three', 'two'}

In [18]:
sample_set[3]

TypeError: 'set' object is not subscriptable

#### Mutable

##### Doesn't allow duplicates

##### Ordered according to first digit

##### Set elements cannot be retrieved using index

In [22]:
sample_set2 = {1,12,2,21,3,31,22}
sample_set2

{1, 2, 3, 12, 21, 22, 31}

In [23]:
sample_set.add(1000)

In [24]:
sample_set

{1, 1000, 2, 3, 'one', 'three', 'two'}

In [25]:
sample_set2.add(15)
sample_set2

{1, 2, 3, 12, 15, 21, 22, 31}

In [26]:
sample_set.remove(3)
sample_set

{1, 1000, 2, 'one', 'three', 'two'}

##### Dictionaries:

In [29]:
sample_dict={1:"appple", 2:"orange", 3:"banana", 4:4}
sample_dict

{1: 'appple', 2: 'orange', 3: 'banana', 4: 4}

##### Key-value pair data structure

##### Key should be unique and if not it will take the latest one

##### Values can be duplicated but not keys

In [30]:
sample_dict[1]

'appple'

#### dictionary [key]

##### Can retrieve value using key but not vice-versa

##### Modifying key-value pair

In [31]:
sample_dict[4] = "fruits"
sample_dict

{1: 'appple', 2: 'orange', 3: 'banana', 4: 'fruits'}

##### Mutable

##### Adding key-value pair:

In [32]:
sample_dict[10] = "messi"

In [33]:
sample_dict

{1: 'appple', 2: 'orange', 3: 'banana', 4: 'fruits', 10: 'messi'}

##### Deleting key-value pair:

In [34]:
del(sample_dict[2])

In [35]:
sample_dict

{1: 'appple', 3: 'banana', 4: 'fruits', 10: 'messi'}

### 

### 

### NUMPY: Package for multidimensional array

In [40]:
import numpy as np

In [41]:
l=[5,6,8]
np.array(l)

array([5, 6, 8])

In [42]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
np.arange(3,30,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [44]:
np.arange(1,5,1)

array([1, 2, 3, 4])

In [45]:
np.arange(1,5)

array([1, 2, 3, 4])

##### np.arange (start(inclusive -> open interval), stop(exclusive -> closed interval), step)

##### np.arange() == for i in range()

### Shift + Tab -> Details of a function

In [46]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.zeros(10,str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [50]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [51]:
np.zeros(0,dtype=int)

array([], dtype=int64)

In [53]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [54]:
np.ones(10,str)

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [55]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### np.ones ((rows,columns))

In [58]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

##### linspace (start,stop,divider)

In [59]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [60]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

##### eye(n) -> identity matrix n rows and n columns

In [61]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])