# (6 December) NumPy and Panda

In [4]:
import numpy as np

##### numpy.random.rand(m,n) -> generates an array of random numbers between 0 and 1 in a mxn matrix

In [15]:
np.random.rand(3,3)

array([[0.80360492, 0.01847179, 0.1545688 ],
       [0.74470341, 0.7021175 , 0.10333424],
       [0.08922935, 0.64083022, 0.33803787]])

In [4]:
np.random.rand(4,4)

array([[0.42972461, 0.66490265, 0.65056022, 0.84612747],
       [0.30412617, 0.15105139, 0.9244555 , 0.65173966],
       [0.63360149, 0.66112669, 0.34555228, 0.63915168],
       [0.75164941, 0.49525008, 0.55726456, 0.19215115]])

##### numpy.random.randn(m,n) -> generates an array of random numbers (positive and negative) in a mxn matrix

In [5]:
np.random.randn(3,3)

array([[ 0.27904347, -1.25989562,  1.11696074],
       [-0.9150342 ,  0.0020028 ,  1.02482367],
       [-1.86185807,  0.04545146, -0.64276685]])

In [6]:
np.random.randn(5,5)

array([[-0.55887444, -2.49968651, -0.54592193,  0.35334658, -0.91475895],
       [ 0.27120673, -1.44696493,  1.27772925,  0.49415342,  1.72339494],
       [ 1.53670656, -0.93694692, -0.24803974, -1.68622209,  2.12934354],
       [-0.69990422,  0.26344268,  0.26274437,  0.55679999,  0.67657582],
       [ 0.95855286, -2.91479383,  1.71308809,  0.5215337 ,  0.10964297]])

##### numpy.random.randint(starting_val, ending_val, n) -> generates an array of n random numbers between starting_val and ending_val

In [9]:
np.random.randint(1,100)

24

In [10]:
np.random.randint(1,100,50)

array([14, 65, 28, 43, 62, 47, 47, 17, 30, 54, 53, 80,  6, 39, 68, 86, 40,
        5, 54, 37, 63, 21, 37, 44, 23,  4, 80, 77, 68, 72,  6, 48, 86, 35,
       24,  5, 48,  4, 83, 54, 98, 38,  9, 26, 84, 35, 52,  1, 89, 75])

In [5]:
np.random.randint(1,100,2)

array([88, 17])

##### sample_array.reshape(m,n) -> reshapes the sample array into a matrix of dimension mxn

In [22]:
sample_array = np.arange(0,16,1)

In [23]:
sample_array.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
sample_array.reshape(4,5)

ValueError: cannot reshape array of size 16 into shape (4,5)

##### cannot reshape array of size 16 into shape (4,5)

##### rand_array.min() -> returns minimum valued element in the array

In [27]:
rand_array = np.random.randint(1,100,25)

In [28]:
rand_array

array([62, 10, 51, 37, 67, 54, 55, 82, 86,  5, 88, 22, 33, 91,  7, 41, 64,
       94, 79, 97, 55, 43,  6, 75, 25])

In [29]:
rand_array.min()

5

In [30]:
rand_array.argmin()

9

##### array.argmin() -> returns index of minimum element

In [33]:
rand_array.dtype

dtype('int32')

##### matrix.T -> returns transpose of matrix

In [34]:
a=np.random.rand(2,3)

In [35]:
a

array([[0.30002524, 0.82611812, 0.12584667],
       [0.29691255, 0.67810425, 0.79976364]])

In [36]:
a.T

array([[0.30002524, 0.29691255],
       [0.82611812, 0.67810425],
       [0.12584667, 0.79976364]])

In [38]:
np.arange(10,20)[3]

13

In [39]:
np.arange(10,20)[3:6]

array([13, 14, 15])

In [41]:
a = np.arange(10,21)

In [42]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
a[4:7]=100

In [44]:
a

array([ 10,  11,  12,  13, 100, 100, 100,  17,  18,  19,  20])

In [45]:
##### changes all values to 100

In [46]:
subset=a[4:8]

In [47]:
subset

array([100, 100, 100,  17])

In [48]:
subset[1:3]=500

In [49]:
subset

array([100, 500, 500,  17])

In [51]:
subset[:]=1000
subset

array([1000, 1000, 1000, 1000])

### 2-D Arrays:

In [147]:
sample_2d_matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
sample_2d_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [64]:
sample_2d_matrix[1,3]

8

##### matrix[x,y] <=> matrix[x][y]

In [63]:
sample_2d_matrix[2,:]

array([ 9, 10, 11, 12])

In [152]:
sample_2d_matrix[:][1]

array([5, 6, 7, 8])

In [153]:
sample_2d_matrix[:,1]

array([ 2,  6, 10, 14])

##### matrix[:,(x,y)] -> column x to column y

##### matrix[(x,y),:] -> row x to row y

In [74]:
sample_2d_matrix[:,(1,2)]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [73]:
sample_2d_matrix[(1,2),:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Selection Techniques:

In [2]:
import numpy as np

In [5]:
sample_array = np.arange(1,20)

In [6]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [7]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [8]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [9]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [10]:
np.max(sample_array)

19

In [11]:
np.min(sample_array)

1

In [12]:
np.argmin(sample_array)

0

In [13]:
np.argmax(sample_array)

18

In [14]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [15]:
np.std(sample_array)

5.477225575051661

In [18]:
##### standard deviation of data set

In [16]:
np.var(sample_array)

30.0

In [19]:
##### variance of data set

In [17]:
np.mean(sample_array)

10.0

In [22]:
arr = np.random.randn(3,5)
arr

array([[-0.88258271,  0.5465399 ,  0.43816159, -0.09157229, -0.84138037],
       [ 0.4205428 , -0.27017261,  1.07737994, -0.05989639, -0.19251839],
       [ 1.07279986,  0.5844414 , -1.04137647,  0.0411723 ,  0.78155179]])

In [23]:
np.round(arr,decimals=2)

array([[-0.88,  0.55,  0.44, -0.09, -0.84],
       [ 0.42, -0.27,  1.08, -0.06, -0.19],
       [ 1.07,  0.58, -1.04,  0.04,  0.78]])

In [24]:
l=["a","b","c","d","a","d"]
np.unique(l)

array(['a', 'b', 'c', 'd'], dtype='<U1')

######   

## PANDAS: Package to create data, table and manipulate:

In [27]:
import pandas as p
import numpy as n

In [28]:
labels=["a","b","c","d"]

In [36]:
sample_list = [10,20,30,40]

In [31]:
arr = np.array([1,2,3,4])

In [32]:
dict = {"e":10, "f":20, "g":30, "h":40}

##### pandas.Series (data=[ ],index=[ ])

In [37]:
p.Series(data=sample_list)

0    10
1    20
2    30
3    40
dtype: int64

In [38]:
p.Series(data=sample_list,index=labels)

a    10
b    20
c    30
d    40
dtype: int64

In [39]:
p.Series(sample_list,labels)

a    10
b    20
c    30
d    40
dtype: int64

In [40]:
p.Series(dict)

e    10
f    20
g    30
h    40
dtype: int64

### Pandas dataframe and indexing:

In [48]:
sports1=p.Series(data=[1,2,3,4],index=["football","cricket","table tennis","skateboarding"])
sports1

football         1
cricket          2
table tennis     3
skateboarding    4
dtype: int64

In [49]:
sports1["football"]

1

In [53]:
sports2=p.Series(data=[10,20,30,40],index=["football","cricket","table tennis","golf"])
sports2

football        10
cricket         20
table tennis    30
golf            40
dtype: int64

In [54]:
sports1+sports2

cricket          22.0
football         11.0
golf              NaN
skateboarding     NaN
table tennis     33.0
dtype: float64

##### NaN -> because to perform operations the data should be present in both the pandas Series

### Data frame

In [109]:
d = p.DataFrame(data=np.random.rand(5,5), index="A B C D E".split(), columns="S1 S2 S3 S4 S5".split())
d

S1        S2        S3        S4        S5
A  0.897690  0.581450  0.989235  0.157353  0.368251
B  0.912737  0.337831  0.912136  0.287387  0.215041
C  0.769809  0.089461  0.364131  0.825308  0.053372
D  0.114735  0.659640  0.517848  0.686611  0.470896
E  0.043856  0.794977  0.750711  0.179703  0.444798

In [64]:
d["S1"]

A    0.543493
B    0.966086
C    0.646139
D    0.980128
E    0.639087
Name: S1, dtype: float64

In [68]:
d["Separate"]=d["S2"]+d["S5"]

In [69]:
d

S1        S2        S3        S4        S5  Separate
A  0.129392  0.077424  0.968103  0.092183  0.051968  0.129392
B  1.317663  0.439139  0.184367  0.480148  0.878524  1.317663
C  0.989583  0.646751  0.501218  0.269245  0.342832  0.989583
D  1.097140  0.665524  0.367637  0.092598  0.431616  1.097140
E  0.742139  0.371207  0.232335  0.927135  0.370931  0.742139

In [70]:
##### new column created

In [84]:
data_barca_all_time=p.DataFrame(data={"Player":["Player_1", "Player_2", "Player_3", "Player_4", "Player_5"],"Name":["Messi","Neymar","Suarez","Xavi","Iniesta"]}, columns="Player Name".split())
data_barca_all_time

Player     Name
0  Player_1    Messi
1  Player_2   Neymar
2  Player_3   Suarez
3  Player_4     Xavi
4  Player_5  Iniesta

##### also done by

In [86]:
data_set={"Player":["Player_1", "Player_2", "Player_3", "Player_4", "Player_5"],"Name":["Messi","Neymar","Suarez","Xavi","Iniesta"]}
df3=p.DataFrame(data_set)
df3

Player     Name
0  Player_1    Messi
1  Player_2   Neymar
2  Player_3   Suarez
3  Player_4     Xavi
4  Player_5  Iniesta

In [88]:
df3["Player"]

0    Player_1
1    Player_2
2    Player_3
3    Player_4
4    Player_5
Name: Player, dtype: object

In [91]:
df3[["Player","Name"]]

Player     Name
0  Player_1    Messi
1  Player_2   Neymar
2  Player_3   Suarez
3  Player_4     Xavi
4  Player_5  Iniesta

In [92]:
df4=df3

##### data_frame.drop (name, axis = 0 or 1)
##### axis=1 refers to the column deletion
##### axis=0 (Default) refers to row deletion

In [108]:
df4.drop("Player",axis=1)

Name
0    Messi
1   Neymar
2   Suarez
3     Xavi
4  Iniesta

In [107]:
df4.drop(1,axis=0)

Player     Name
0  Player_1    Messi
2  Player_3   Suarez
3  Player_4     Xavi
4  Player_5  Iniesta

In [110]:
df4.drop(1)

Player     Name
0  Player_1    Messi
2  Player_3   Suarez
3  Player_4     Xavi
4  Player_5  Iniesta

In [112]:
##### same

##### 

### Importing datasets using Pandas:

In [118]:
data_file=p.read_csv("https://raw.githubusercontent.com/Premalatha-success/Financial-Analytics-Loan-Approval-Prediction/main/loan_prediction.csv")
data_file

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

##### df = p.read_csv("csv link")
##### df = p.read_excel("excel link")

In [136]:
##### df.head(x) -> displays first x rows
##### df.tail(x) -> displays last x rows

In [131]:
data_file.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [132]:
data_file.tail()

Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [137]:
##### df.sample(x) -> displays x random sample rows

In [140]:
data_file.sample()

Loan_ID Gender Married Dependents     Education Self_Employed  \
94  LP001325   Male      No          0  Not Graduate            No   

    ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
94             3620                0.0        25.0             120.0   

    Credit_History Property_Area Loan_Status  
94             1.0     Semiurban           Y

In [122]:
data_file.shape

(614, 13)

In [123]:
data_file.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [142]:
data_file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [155]:
data_file.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [144]:
data_file.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [143]:
data_file.describe(include="all")

Loan_ID Gender Married Dependents Education Self_Employed  \
count        614    601     611        599       614           582   
unique       614      2       2          4         2             2   
top     LP001002   Male     Yes          0  Graduate            No   
freq           1    489     398        345       480           500   
mean         NaN    NaN     NaN        NaN       NaN           NaN   
std          NaN    NaN     NaN        NaN       NaN           NaN   
min          NaN    NaN     NaN        NaN       NaN           NaN   
25%          NaN    NaN     NaN        NaN       NaN           NaN   
50%          NaN    NaN     NaN        NaN       NaN           NaN   
75%          NaN    NaN     NaN        NaN       NaN           NaN   
max          NaN    NaN     NaN        NaN       NaN           NaN   

        ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count        614.000000         614.000000  592.000000         600.00000   
unique              NaN                NaN         NaN               NaN   
top                 NaN                NaN         NaN               NaN   
freq                NaN                NaN         NaN               NaN   
mean        5403.459283        1621.245798  146.412162         342.00000   
std         6109.041673        2926.248369   85.587325          65.12041   
min          150.000000           0.000000    9.000000          12.00000   
25%         2877.500000           0.000000  100.000000         360.00000   
50%         3812.500000        1188.500000  128.000000         360.00000   
75%         5795.000000        2297.250000  168.000000         360.00000   
max        81000.000000       41667.000000  700.000000         480.00000   

        Credit_History Property_Area Loan_Status  
count       564.000000           614         614  
unique             NaN             3           2  
top                NaN     Semiurban           Y  
freq               NaN           233         422  
mean          0.842199           NaN         NaN  
std           0.364878           NaN         NaN  
min           0.000000           NaN         NaN  
25%           1.000000           NaN         NaN  
50%           1.000000           NaN         NaN  
75%           1.000000           NaN         NaN  
max           1.000000           NaN         NaN